import PromptCard from "./PromptCard";

//It returns a section element that contains a heading, a paragraph, and a list of PromptCard components. The heading displays the name prop passed to the component, and the paragraph displays the desc prop. The list of PromptCard components is generated by mapping over the data prop and passing each item in the array as a prop to the PromptCard component. The handleEdit and handleDelete props are optional functions that can be passed to the PromptCard component to handle edit and delete functionality. When passed, they are called with the post object as an argument.
const Profile = ({ name, desc, data, handleEdit, handleDelete }) => {
  return (
    <section className='w-full'>
      <h1 className='head_text text-left'>
        <span className='blue_gradient'>{name} Profile</span>
      </h1>
      <p className='desc text-left'>{desc}</p>

      <div className='mt-10 prompt_layout'>
        {data.map((post) => (
          <PromptCard
            key={post._id}
            post={post}
            handleEdit={() => handleEdit && handleEdit(post)}
            handleDelete={() => handleDelete && handleDelete(post)}
          />
        ))}
      </div>
    </section>
  );
};

export default Profile;